# Generated by Django 5.2.8 on 2025-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_ticket_estatus_alter_ticket_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignado',
            field=models.CharField(blank=True, choices=[('Juan Perez', 'Juan Perez'), ('Maria Lopez', 'Maria Lopez'), ('Carlos Diaz', 'Carlos Diaz')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estatus',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('En progreso', 'En progreso'), ('Completado', 'Completado')], default='Nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ubicacion',
            field=models.CharField(choices=[('Flute Automation', 'Flute Automation'), ('Flute Machining', 'Flute Machining')], max_length=50),
        ),
    ]
